### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by machour**
All tests are running except the ones involving active-record (Affected by https://github.com/yiisoft/active-record/issues/23).

Also noticed an important change, with Yii2 the `@app` alias was always defined (running tests on yii2-twig), whereas here, I need to explicitly define it in `config/tests.php`. 
Is it normal that `@app` is gone?

### CODE REVIEW

**Comment by machour** [comment]
@schmunk42 I think I need some guidance here.

Since [this commit](https://github.com/yiisoft/yii-jquery/commit/2f82d53568038447179be1fcd309a15a9f6265c1) in yii-jquery, requiring `yiisoft/yii-jquery` in twig's composer.json isn't enough to have composer download the javascript assets.

I tried adding `"foxy/foxy": "^1.0.0"` in my requirements (dev or not), but it doesn't seem to read and install from `yiisoft/yii-jquery/package.json`. Isn't that what it's supposed to do ?

Using "wikimedia/composer-merge-plugin": "dev-master" for now.

**Comment by hiqsol** [comment]
I can't make good default guess for `@app` alias right now. We'll see later.
Setting it in `config/tests.php` is good for now.

**Comment by hiqsol** [comment]
Concerning `foxy` - it worked for me. I think you've missed some detail.

**Comment by schmunk42** [comment]
You need npm (or yarn) for foxy, but it should throw a warning if it can't find the binary.

The error in the tests is from a SQL statement?! Why is Twig needing a DB?

**Comment by machour** [comment]
I do have npm & yarn on my system. I think we're missing something in yiisoft/yii-jquery composer file (`extra: { foxy: true }` or a require-dev to `foxy/foxy`) to make foxy pick up the package.json file.

As for the errors, [some tests](https://github.com/yiisoft/yii-twig/blob/master/tests/ViewRendererTest.php#L118) are using ActiveRecord ¯\\_(ツ)_/¯.

**Comment by machour** [comment]
https://github.com/fxpio/foxy/blob/master/Resources/doc/usage.md#use-the-plugin-in-php-library

**Pull request merged**
